#platform :ios, '9.0'
use_frameworks!
workspace 'SymAgent'


# shared pods
pod 'SwiftyJSON'
pod 'AsyncSwift'
pod 'SensingKit'

# SymAgent
target :SymAgent do
    project 'SymAgent/SymAgent.xcodeproj'
    
end


#the app
target :SSPApp do
  project 'SSPApp.xcodeproj'

  pod 'Charts', '3.0.2'
  pod 'DrawerController', '3.0.0'
end
