#platform :ios, '9.0'
use_frameworks!
workspace 'SymAgent'


# shared pods
pod 'SwiftyJSON'

# SymAgent
target :SymAgent do
    project 'SymAgent/SymAgent.xcodeproj'
end


#the app
target :SSPApp do
  project 'SSPApp.xcodeproj'

  pod 'Charts'
  pod 'AsyncSwift'
  pod 'DrawerController'
end
